#executar -> docker-compose up --build
version: '3'

services:
  db:
    build: ./docker-config/postgres
    networks:
      - webnet
    volumes:
      - ${DB_DATA_FOLDER}:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432"
    labels:
      co.elastic.metrics/module: postgresql
      co.elastic.metrics/metricsets: database,bgwriter,activity,statement
      co.elastic.metrics/period: 10s
     # there's 2 & to escape it inside a docker compose file
      co.elastic.metrics/hosts: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@$${data.host}:5432'
  web:
    build: .
    command:
      - ./wait-for-postgres.sh
      - db
      - parsifal
      - ${POSTGRES_PASSWORD}
      - ./app-entrypoint.sh
    depends_on:
      - db
    networks:
      - webnet    
    volumes:
      - ${STATIC_FOLDER}:/static 
      - ${MEDIA_FOLDER}:/media 
    restart: always
    labels:
      co.elastic.metrics/module: nginx
      co.elastic.metrics/metricsets: stubstatus
      co.elastic.metrics/period: 10s
      # there's 2 & to escape it inside a docker compose file
      co.elastic.metrics/hosts: '$${data.host}:10080' 
  r:
    build: ./docker-config/r
    networks:
      - webnet    
    restart: always 
  staticweb:
    image: nginx:latest
    ports:
      - "${STATIC_WEB_PORT}:80"
    volumes:
      - ${ROOT_FOLDER}:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - web
    networks:
      - webnet
    restart: always
    env_file:
      - .env

networks:
  webnet:
