#executar -> docker-compose up --build
version: '3'

services:
  db:
    image: postgres:10.1-alpine
    networks:
      - webnet
    volumes:
      - /docker-volumes/parsifal/db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 7001:5432
  web:
    build: .
    command:
      - ./wait-for-postgres.sh
      - db
      - parsifal
      - ${POSTGRES_PASSWORD}
      - ./app-entrypoint.sh
        #command: ["./wait-for-postgres.sh", "db", "parsifal", $POSTGRES_PASSWORD,"./app-entrypoint.sh"]
    ports:
      - 7000:8000
    depends_on:
      - db
    networks:
      - webnet    
    volumes:
      - /docker-volumes/parsifal/web/static:/static 
    restart: always  
networks:
  webnet:
