#executar -> docker-compose up --build
version: '3'

services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_DB: parsifal
      POSTGRES_USER: parsifal
      POSTGRES_PASSWORD: parsifal
    networks:
      - webnet
  web:
    build: .
    command: ["./wait-for-postgres.sh", "db", "./parsifal-entrypoint.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - webnet       
networks:
  webnet:

