#executar -> docker-compose up --build
version: '3'

services:
  db:
    image: postgres:10.1-alpine
    networks:
      - webnet
    volumes:
      - ${DB_DATA_FOLDER}:/var/lib/postgresql/data
    restart: always
#    ports:
#      - 7001:5432
    env_file:
      - .env
  web:
    build: .
    command:
      - ./wait-for-postgres.sh
      - db
      - parsifal
      - ${POSTGRES_PASSWORD}
      - ./app-entrypoint.sh
    depends_on:
      - db
    networks:
      - webnet    
    volumes:
      - ${STATIC_FOLDER}:/static 
      - ${MEDIA_FOLDER}:/media 
    restart: always 
  staticweb:
    image: nginx:latest
    container_name: staticweb
    ports:
      - "${STATIC_WEB_PORT}:80"
    volumes:
      - ${ROOT_FOLDER}:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - web
    networks:
      - webnet
    env_file:
      - .env

networks:
  webnet:
